#!/usr/bin/env python3

# Script para reconstruir tanto el blog como la sección de últimas lecturas
# y para actualizar los index tanto de gémini como de la versión web
# 
# Dependencias: (pip3 install ...)
#  - lxml
#  - beautifulsoup4
#  - feedgen
#  - markdown

from string import Template
from datetime import datetime, timezone
import os
import sys
import re
from string import Template
import requests
from bs4 import BeautifulSoup
from feedgen.feed import FeedGenerator
import urllib.parse
import markdown
import csv

HOME=os.getenv("HOME")

HTML_ROOT="/var/www/html"
INSTALL_BUILD=HOME+"/web"

HTML_BLOG="/blog"
HTML_STATIC="/static"

POSTS_ROOT=INSTALL_BUILD+"/blog"
STATIC_ROOT=INSTALL_BUILD+"/static"
POSTS_INDEX=POSTS_ROOT+"/INDEX"

HTML_FILE_BOOKS=HTML_ROOT+"/books.html"
HTML_TEMPLATE_BOOKS=INSTALL_BUILD+"/templates/books-template.html"

HTML_TEMPLATE_BLOG=INSTALL_BUILD+"/templates/blog-template.html"
HTML_TEMPLATE_BLOG_POST=INSTALL_BUILD+"/templates/blog-post-template.html"



##
##
##  FUNCIONES PARA EL BLOG
##
##

post_files=[]
static_files=[]

def extractTitleFromMD(mdcontent):
    regex = r"^# (.+)"
    test_str=mdcontent
    matches = re.search(regex, test_str, re.MULTILINE)
    if (matches==None):
        return ""
    return matches.groups()[0]


def buildPost(post):
  mdfile=post[0]
  date=post[1]
  tags=post[2]
  
  pathFile="{dir}/{file}".format(dir=POSTS_ROOT,file=mdfile)
  f= open(pathFile)
  mdcontent=f.read()
  title=extractTitleFromMD(mdcontent).strip("#")

  with open(HTML_TEMPLATE_BLOG_POST) as t:
    postTemplate=Template(t.read())
    if postTemplate=="":
      return

  # Build the HTML
  rawhtml = markdown.markdown(mdcontent,extensions=['tables','fenced_code'])
  htmlpost = rawhtml
  htmlpost=htmlpost.replace("<p><img","<p class=\"imagen\"><img")
  html=postTemplate.substitute(post=htmlpost,post_title=title)
  with open(HTML_ROOT+HTML_BLOG+"/"+mdfile+".html","w") as fh:
    fh.write(html)
    fh.close();
  print ("Build "+mdfile+".html")

  post_files.append((mdfile,title,date,mdcontent,tags,rawhtml))



def buildStatic(mdfile):

  pathFile="{dir}/{file}".format(dir=STATIC_ROOT,file=mdfile)
  f= open(pathFile)
  mdcontent=f.read()
  title=extractTitleFromMD(mdcontent).strip("#")

  with open(HTML_TEMPLATE_BLOG_POST) as t:  # Usamos la misma plantilla que para los artículos del blog
    postTemplate=Template(t.read())
    if postTemplate=="":
      return

  # Build the HTML
  rawhtml = markdown.markdown(mdcontent,extensions=['tables','fenced_code'])
  htmlpost = rawhtml
  htmlpost=htmlpost.replace("<p><img","<p class=\"imagen\"><img")
  html=postTemplate.substitute(post=htmlpost,post_title=title)
  with open(HTML_ROOT+HTML_STATIC+"/"+mdfile+".html","w") as fh:
    fh.write(html)
    fh.close();
  print ("Build "+mdfile+".html")

    
def fileChanged(f1,f2):
  try:
    # Compare mtime
    sf1=os.stat(f1).st_mtime
    sf2=os.stat(f2).st_mtime
    if sf2<sf1:
      return True
    return False
  except:
    return True


def buildHTMLIndexBlog():
  post_files.reverse()
  postsList=""
  for fileInfo in post_files:
    dt=datetime.strptime(fileInfo[2],"%d/%m/%Y")
    post="<li><a href={url}.html>{text}</a><p class='post-meta'>({date} - <span class='tags'>{tags}</span>)</p></li>".format(
      url=fileInfo[0],
      text=fileInfo[1],
      tags=fileInfo[4].replace(",",", "),
      date=localeDate(dt.strftime("%B %Y")))
    postsList+="\n"+post

  with open(HTML_TEMPLATE_BLOG) as t:
    strTmpl=t.read()
    tmpl=Template(strTmpl)
    html=tmpl.substitute(posts=postsList)
      
    with open(HTML_ROOT+HTML_BLOG+"/index.html","w") as o:
      o.write(html)
      o.close()
      print ("Build blog.html")
     
  
        
def getPosts():
  posts=[]
  
  with open(POSTS_INDEX) as f:
    indexLines=f.readlines()

  for line in indexLines:
    fields=re.sub(r'\s+'," ",line).split(" ")
    filename=""
    date=""
    tags=""
    if len(fields)>0:
      date=fields[0].strip("\n")
      filename=fields[1].strip("\n")
      if len(fields)>2:
        tags=fields[2].strip("\n")
    else:
      filename=fields[0].strip("\n")

    if len(filename)>0:
      posts.append([filename,date,tags])
      
  return posts


def buildBlog(htmlonly=False):
  if not os.path.exists(HTML_ROOT+HTML_BLOG):
    os.makedirs(HTML_ROOT+HTML_BLOG)

  posts=getPosts()
  for post in posts:
    buildPost(post)

  buildHTMLIndexBlog()




def buildStatics():
  if not os.path.exists(HTML_ROOT+HTML_STATIC):
    os.makedirs(HTML_ROOT+HTML_STATIC)

  statics = [f for f in os.listdir(STATIC_ROOT)]
  for static in statics:
    buildStatic(static)



def buildFeed():
  fg = FeedGenerator()
  fg.link( href='http://panicerror.org/blog/atom.xml', rel='self' )
  fg.title('PanicError')
  fg.author( {'name':'sdemingo','email':'sdemingo@texto-plano.xyz'} )
  fg.language('es')
  fg.id("http://panicerror.org/blog/atom.xml")
  
  for fileInfo in post_files:
    fe = fg.add_entry()
    url="http://"+urllib.parse.quote("panicerror.org/blog/"+fileInfo[0]+".html")
    fe.id(url)
    fe.title(fileInfo[1])
    tdate=datetime.strptime(fileInfo[2],"%d/%m/%Y").replace(tzinfo=timezone.utc)
    fe.published(tdate)
    fe.updated(tdate)
    fe.content(fileInfo[5],type="html")
    fe.link(href=url)
  
  atomfeed = fg.atom_str(pretty=True)
  fg.atom_file(INSTALL_BUILD+"/atom.xml")

  cmd="cp {dir1}/atom.xml {dir2}/blog/atom.xml".format(
    dir1=INSTALL_BUILD,
    dir2=HTML_ROOT)
  print ("Build atom.xml")
  os.system(cmd)




    
##
##
## FUNCIONES PARA LOS LIBROS
##
##

def date_from_row(row):
    return datetime.strptime(row[2], '%d/%m/%y')


def procesa_libro_leyendo(filename,fecha_formateada):
        titulo=""
        autor=""
        origen=""
        with open(HOME+"/notebook/libros/leyendo/"+filename,"r") as f:
            lineas=f.readlines()
            if (len(lineas)>=1):
                titulo=lineas[0].strip("#\n ")

            if (len(lineas)>=2):
                autor=lineas[1].strip("\n ")

            if (len(lineas)>=3):
                origen=lineas[2].strip("\n ")

            f.close()
        
        return (titulo,autor,fecha_formateada,origen)
        



def getReads():
  reads=[]
  currently=[]
  cur_year=str(datetime.today().year).removeprefix("20")
  cur_year_books=0

  with open(HOME+"/notebook/libros/ficcion.csv") as csv_file:
    csv_reader = list(reversed(list(csv.reader(csv_file, delimiter=';'))))
    for row in csv_reader:
      if len(row)>2 and row[2].strip()!="-":
        reads.append((row[0].strip(),row[1].strip(),row[2].strip()))
        if "/"+cur_year in row[2].strip():
          cur_year_books+=1


  with open(HOME+"/notebook/libros/noficcion.csv") as csv_file:
    csv_reader = list(reversed(list(csv.reader(csv_file, delimiter=';'))))
    for row in csv_reader:
      if len(row)>2 and row[2].strip()!="-":
        reads.append((row[0].strip(),row[1].strip(),row[2].strip()))
        if "/"+cur_year in row[2].strip():
          cur_year_books+=1

  # Ordenar array de filas (de ficción y no ficción) por fecha
  reads = sorted(reads, key=date_from_row,reverse=True)[:10]

  # Relleno currently con los libros leyendo actualmente
  for filename in os.listdir(os.path.expanduser(HOME+"/notebook/libros/leyendo")):
    try:
      try:
        # Extraemos solo los primeros 14 caracteres si el nombre es YmdHMS
        fecha_obj = datetime.strptime(filename[:14], "%Y%m%d%H%M%S")
        fecha_formateada = fecha_obj.strftime("%d/%m/%y")
      except ValueError:
        continue  # El fichero no es de registro de libro y se ignora

      datos_libro=procesa_libro_leyendo(filename,fecha_formateada)
      currently.append((datos_libro[0], datos_libro[1]))

    except Exception as e:
      print (e)
      continue

  return (reads[:20],currently[:20],cur_year_books)


def buildListHTML(reads):
  readsHTML=""
  for r in reads:    
      readsHTML+="<li>{title} - <span class='author'>{author}</span></li>".format(author=r[1],title=r[0])      

  return readsHTML



def buildBooks(htmlonly=False):

  todayDate=datetime.today().strftime("%d/%m/%Y")
  (lastReads,curReads,readsInYear)=getReads()
  lastList=buildListHTML(lastReads)
  curList=buildListHTML(curReads)

  with open(HTML_TEMPLATE_BOOKS) as t:
    strTmpl=t.read()
    tmpl=Template(strTmpl)
    html=tmpl.substitute(lasts=lastList,cur=curList,lastDate=todayDate,reads=readsInYear)
    
    with open(HTML_FILE_BOOKS,"w") as o:
      o.write(html)
      print ("Build books.html")






##
##
## FUNCIONES GENERALES
##
##

months={"January":"Enero",
        "February":"Febrero",
        "March":"Marzo",
        "April":"Abril",
        "May":"Mayo",
        "June":"Junio",
        "July":"Julio",
        "August":"Agosto",
        "September":"Septiembre",
        "October":"Octubre",
        "November":"Noviembre",
        "December":"Diciembre"}
        
def localeDate(dstr):
  for i,j in months.items():
    dstr = dstr.replace(i,j)
  return dstr



             
def buildHTMLIndex():
  cmd="cp {dir1}/index-template.html {dir2}/index.html".format(
            dir1=INSTALL_BUILD+"/templates",
            dir2=HTML_ROOT)
  print ("Build index.html")
  os.system(cmd)


def buildCSS():
  cmd="cp {dir1}/estilo.css {dir2}".format(
            dir1=INSTALL_BUILD+"/resources",
            dir2=HTML_ROOT)
  print ("Build estilo.css")
  os.system(cmd)


def buildImages():
  cmd="cp {dir1}/* {dir2}".format(
            dir1=INSTALL_BUILD+"/img",
            dir2=HTML_ROOT+"/img")
  print ("Build images")
  os.system(cmd)
  
  

if __name__=='__main__':

    
  if len(sys.argv)<2:
    print ("\t\t build [ --all | --blog | --books | --htmlonly ] ")
    sys.exit(0)

  if sys.argv[1]=="--books":
    buildBooks()
    sys.exit(0)

  if sys.argv[1]=="--blog":
    buildBlog()
    buildImages()
    sys.exit(0)

  if sys.argv[1]=="--htmlonly":
    buildBlog(True)
    buildStatics()
    buildBooks(True)
    buildHTMLIndex()
    buildCSS()
    buildFeed()
    buildImages()

  if sys.argv[1]=="--all":
    buildBlog()
    buildStatics()
    buildBooks()
    buildHTMLIndex()
    buildCSS()
    buildFeed()
    buildImages()

